### ISSUE TITLE
[QUESTION] Ability to use mods

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [Unkzittys/DokiDokiLiteratureClub_AndroidPort#3]
Heya, is it possible to use mods at all with this? Really would like to play some DDLC mods honestly but I don't know how I'd go about adding them to be played

**Comment by Unkzittys** [comment]
Unfortunately, it's not possible in the version of Ren'Py the game uses without rebuilding the entire project. The closest thing to using mods would be the patch functionality that arrived in Ren'Py 7.2, however the code for almost all DDLC mods needs to individually have ported functions.

I unfortunately cannot port mods here on GitHub (it'll flood my profile and make the navigation hard), but I allow you and anyone to use the port code to base your mod ports on.
